# Generated by Django 5.1.1 on 2024-10-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fname', models.CharField(max_length=40)),
                ('doctor_lname', models.CharField(max_length=50)),
                ('doctor_specialty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fname', models.CharField(max_length=40)),
                ('patient_lname', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=20)),
                ('patient_doctor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_fname', models.CharField(max_length=40)),
                ('specialist_lname', models.CharField(max_length=50)),
                ('specialist_specialty', models.CharField(max_length=50)),
            ],
        ),
    ]
